/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pramod
 */
public class admin_Regd extends javax.swing.JFrame {

    /**
     * Creates new form admin_Regd
     */
    public admin_Regd() {
        initComponents();
        connect();
    }
    
    
    
    
String s;
     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void connect()
    {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root", "Prbarik528@gmail.com");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(admin_Regd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    static class valid
            {     
     public static boolean isValid(String email)
     {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        sb = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtregd = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        home = new javax.swing.JLabel();
        ri = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        ei = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        HOME = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Upload Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        lb.setText(" ");
        lb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 160, 160));

        sb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s+b.png"))); // NOI18N
        sb.setText(" ");
        sb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sbMouseExited(evt);
            }
        });
        getContentPane().add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close2.png"))); // NOI18N
        jLabel13.setText(" ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Admin Registration Form");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (7).png"))); // NOI18N
        jLabel11.setText(" ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (6).png"))); // NOI18N
        jLabel10.setText(" ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (5).png"))); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (4).png"))); // NOI18N
        jLabel8.setText(" ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminn-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, 113));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("ADMIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Regd_ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 192, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Email_ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Phone_NO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        txtregd.setBackground(new java.awt.Color(255, 102, 0));
        txtregd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtregd.setText(" ");
        txtregd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregdActionPerformed(evt);
            }
        });
        getContentPane().add(txtregd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 271, 30));

        txtemail.setBackground(new java.awt.Color(255, 102, 0));
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setText(" ");
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 271, 30));

        txtphone.setBackground(new java.awt.Color(255, 102, 0));
        txtphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtphone.setText(" ");
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 271, 32));

        txtname.setBackground(new java.awt.Color(255, 102, 0));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 271, 28));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png"))); // NOI18N
        home.setText(" ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        ri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ri.setForeground(new java.awt.Color(255, 0, 0));
        ri.setText("  ");
        getContentPane().add(ri, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 190, 20));

        nm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 0, 0));
        nm.setText(" ");
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 190, 20));

        ei.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ei.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ei, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 190, 20));

        ph.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ph.setForeground(new java.awt.Color(255, 0, 0));
        ph.setText(" ");
        getContentPane().add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 220, 20));

        HOME.setForeground(new java.awt.Color(255, 0, 0));
        HOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Blog-CIMA.png"))); // NOI18N
        HOME.setText(" ");
        getContentPane().add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtregdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregdActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png")));
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+y.png")));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+g.png")));
        new welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void sbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMouseExited
        // TODO add your handling code here:
        sb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s+b.png")));
    }//GEN-LAST:event_sbMouseExited

    private void sbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMouseEntered
        // TODO add your handling code here:
        sb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s+r.png")));
    }//GEN-LAST:event_sbMouseEntered

    private void sbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMouseClicked
        // TODO add your handling code here:
        boolean check=valid.isValid(txtemail.getText().trim());
        if(check)
        {
            //JOptionPane.showMessageDialog(this,"email varified"  );
        }
        else if(txtemail.getText().trim().isEmpty())
        {
            
        }
        else
        {
            ei.setText("Invalid email ID");
            JOptionPane.showMessageDialog(this,"Invalid Email"  );
            
        }
        
        
        
        if(txtregd.getText().trim().isEmpty() && txtname.getText().trim().isEmpty() && txtemail.getText().trim().isEmpty() &&
           txtphone.getText().trim().isEmpty() )
        {
            ri.setText(" * Field requied");
            nm.setText(" * Field requied");
            ei.setText(" * Field requied");
            ph.setText(" * Field requied");
             
        }
        else
        {
            ri.setText(" ");
            nm.setText(" ");
            ei.setText(" ");
            ph.setText(" ");
        }
     
         try {
           
            String regd = txtregd.getText();
            String name = txtname.getText();
            String email = txtemail.getText();
            String phone = txtphone.getText();
            InputStream is = null;
             try {
                 is = new FileInputStream(new File(s));
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(admin_Regd.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            pst= con.prepareStatement("INSERT INTO `online_exam`.`admin`(`RegdID`,`Name`,`Email`,`Phone`,`image`)values(?,?,?,?,?)");
            pst.setString(1,regd);
            pst.setString(2,name);
            pst.setString(3,email);
            pst.setString(4,phone);
             pst.setBlob(5,is);
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record added");
                txtregd.setText("");
                txtname.setText("");
                txtemail.setText("");
                txtphone.setText("");
                //txtname.requestFocus();
                //load();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    
    }//GEN-LAST:event_sbMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             JFileChooser fileChooser = new JFileChooser();
          fileChooser.setCurrentDirectory(new File(System.getProperty( "user.home")));
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
          fileChooser.addChoosableFileFilter(filter);
          int result = fileChooser.showSaveDialog(null);
          if(result == JFileChooser.APPROVE_OPTION)
            {
               File selectedFile = fileChooser.getSelectedFile();
               String path = selectedFile.getAbsolutePath();
               lb.setIcon(ResizeImage(path));
               s = path;
            }
          else if(result == JFileChooser.CANCEL_OPTION)
          {
            System.out.println("No Data");
            
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( HOME,"confirm if you Want to Exit","ONLINE EXAMINATION APPLICATIOM",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
         {
             txtname.setEditable(true);
         }
         else
         {
             txtname.setEditable(false);
             nm.setText("Character's only allowed");
             JOptionPane.showMessageDialog(this, "Plaese Enter only Character ");
             
            
         }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        String ph1=txtphone.getText();
        int length=ph1.length();
        
        char c=evt.getKeyChar();
         if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
         {
             if(length<11){
             txtphone.setEditable(true);
            // ph.setText("  Number's only allowed");
             //JOptionPane.showMessageDialog(this, "Plaese Enetr only number's");
             }
             else
             {
                 txtphone.setEditable(false);
                   //ph.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, " Can't exceed more than 10 digit");
             }
         }
         else
         {
           //  txtphone.setEditable(true);
            // ph.setText("Number's only allowed");
            // JOptionPane.showMessageDialog(this, "Plaese Enetr only Character ");
             
             if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                txtphone.setEditable(true); 
             }
             else
             {
                 txtphone.setEditable(false);
                   ph.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, "Plaese Enter only number's");
             }
             
            
         }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
       /* String email = txtemail.getText();
        if (isValid(email))
        {
            System.out.print("Yes");
        JOptionPane.showMessageDialog(this,"email varified"  );
        }
        else
        {
            JOptionPane.showMessageDialog(this,"email  not varified"  );
            System.out.print("No");
                }*/
    }//GEN-LAST:event_txtemailKeyPressed

     public ImageIcon ResizeImage(String imgPath)
            {
                ImageIcon MyImage = new ImageIcon(imgPath);
                Image img = MyImage.getImage();
                Image newImage = img.getScaledInstance(lb.getWidth(),lb.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                return image;
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_Regd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_Regd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_Regd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_Regd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_Regd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME;
    private javax.swing.JLabel ei;
    private javax.swing.JLabel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel nm;
    private javax.swing.JLabel ph;
    private javax.swing.JLabel ri;
    private javax.swing.JLabel sb;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtregd;
    // End of variables declaration//GEN-END:variables
}
