/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pramod
 */
public class admin_login extends javax.swing.JFrame {

    /**
     * Creates new form admin_login
     */
    public admin_login() {
        initComponents();
        connect();
        this.close.setVisible(false);
    }

     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void connect()
    {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root", "Prbarik528@gmail.com");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(admin_login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jj = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtuname1 = new javax.swing.JPasswordField();
        close = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        regd = new javax.swing.JLabel();
        gm = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jj.setForeground(new java.awt.Color(255, 0, 0));
        jj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jj.setText(" ");
        getContentPane().add(jj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 290, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close2.png"))); // NOI18N
        jLabel7.setText(" ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        txtuname1.setBackground(new java.awt.Color(255, 102, 0));
        txtuname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtuname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 220, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        close.setText(" ");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, 30));

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.png"))); // NOI18N
        open.setText(" ");
        open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openMousePressed(evt);
            }
        });
        getContentPane().add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, 30));

        regd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        regd.setForeground(new java.awt.Color(255, 0, 0));
        regd.setText("Click Here To Registration");
        regd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regdMouseExited(evt);
            }
        });
        getContentPane().add(regd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, -1));

        gm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gm1.png"))); // NOI18N
        gm.setText(" ");
        gm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gmMouseExited(evt);
            }
        });
        getContentPane().add(gm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 40));

        lg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg1.png"))); // NOI18N
        lg.setText(" ");
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgMouseExited(evt);
            }
        });
        getContentPane().add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Admin Login Panel");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        ps.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ps.setForeground(new java.awt.Color(0, 0, 204));
        ps.setText("@Your Password is Registration ID");
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 30));

        un.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        un.setForeground(new java.awt.Color(0, 0, 204));
        un.setText("@user Nmae is Your Name");
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (1).png"))); // NOI18N
        jLabel1.setText(" Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 110, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools.png"))); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtpassword.setBackground(new java.awt.Color(255, 102, 0));
        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpassword.setText(" ");
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 213, 28));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin-settings-male-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("click here to know your detail");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("||");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        login.setBackground(new java.awt.Color(255, 153, 0));
        login.setForeground(new java.awt.Color(255, 153, 0));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login11.jpg"))); // NOI18N
        login.setText(" ");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 620, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmMouseExited
        // TODO add your handling code here:
        gm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gm1.png")));
    }//GEN-LAST:event_gmMouseExited

    private void gmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmMouseEntered
        // TODO add your handling code here:
        gm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gm2.png")));
    }//GEN-LAST:event_gmMouseEntered

    private void gmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmMouseClicked
        // TODO add your handling code here:
         new welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gmMouseClicked

    private void lgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseExited
        // TODO add your handling code here:
        lg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg1.png")));
    }//GEN-LAST:event_lgMouseExited

    private void lgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseEntered
        // TODO add your handling code here:
        lg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg2.png")));
    }//GEN-LAST:event_lgMouseEntered

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
        // TODO add your handling code here:
         
         if(txtpassword.getText().trim().isEmpty() && txtuname1.getText().isEmpty())
       {
           jj.setText("All are fileds are EMpty");
           un.setText("* UserName required");
           ps.setText("* password required");
       }
         else if(txtpassword.getText().trim().isEmpty())
       {
           jj.setText("user name filed is empty");
           un.setText("* user name required");
           ps.setText(" ");
       }
       else if(txtuname1.getText().trim().isEmpty())
       {
           jj.setText("password is filed empty");
           ps.setText("* password required");
            un.setText(" ");
       }
       else
       {
           jj.setText(" ");
           ps.setText(" ");
            un.setText(" ");
       }
      
        
        try{
            
          
           String sql="SELECT * FROM online_exam.admin WHERE `RegdID`= ? and `Name` = ? ";
           pst =con.prepareStatement(sql);
           pst.setString(1, txtuname1.getText());
            pst.setString(2, txtpassword.getText());
           rs=pst.executeQuery();
           if(rs.next())
           {
              JOptionPane.showMessageDialog(this,"you are login"); 
              new Admin().setVisible(true);
             this.setVisible(false);
           }
           else 
           {
              JOptionPane.showMessageDialog(this,"you are login failedfffffffffffffffff");
             // 
           }
         // con.close();
        }catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage() );}
    }//GEN-LAST:event_lgMouseClicked

    private void regdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdMouseExited
        // TODO add your handling code here:
        regd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        regd.setForeground(new java.awt.Color(255, 0, 0));
        regd.setText("Click Here To Registration");
    }//GEN-LAST:event_regdMouseExited

    private void regdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdMouseEntered
        // TODO add your handling code here:
        regd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        regd.setForeground(new java.awt.Color(0, 0, 153));
        regd.setText("Click Here To Registration");
    }//GEN-LAST:event_regdMouseEntered

    private void regdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdMouseClicked
        // TODO add your handling code here:
          new admin_Regd().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_regdMouseClicked

    private void openMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMousePressed
        // TODO add your handling code here:
         close.setVisible(true);
        open.setVisible(false);
         txtuname1.setEchoChar((char)0);
    }//GEN-LAST:event_openMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        open.setVisible(true);
        close.setVisible(false);
         txtuname1.setEchoChar('*');
    }//GEN-LAST:event_closeMousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( login,"confirm if you Want to Exit","ONLINE EXAMINATION APPLICATIOM",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new search().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel gm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jj;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel login;
    private javax.swing.JLabel open;
    private javax.swing.JLabel ps;
    private javax.swing.JLabel regd;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JPasswordField txtuname1;
    private javax.swing.JLabel un;
    // End of variables declaration//GEN-END:variables
}
