/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static online.exam.LOADING.loadingg;

/**
 *
 * @author Pramod
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        connect();
        load();
    }
String s;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        retrive = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jtf = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb.setText(" ");
        lb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 146, 120));

        jButton2.setText("broswer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 167, -1, -1));

        jButton3.setText("add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 167, -1, -1));

        retrive.setText("retrive");
        retrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retriveActionPerformed(evt);
            }
        });
        getContentPane().add(retrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 167, -1, -1));

        lb1.setText(" ");
        lb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb1.setOpaque(true);
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 140));

        jtf.setText(" ");
        getContentPane().add(jtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 105, -1));

        jButton4.setText("retrive");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 270, -1, -1));

        id.setText(" ");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 271, 182, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", " ", " ", " ", " "
            }
        ));
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable2ComponentHidden(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 720, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select your position", "admin", "student", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 //String s;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connect()
    {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root", "Prbarik528@gmail.com");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
     public void load()
    {
        try{
            pst = con.prepareStatement("SELECT * FROM online_exam.student WHERE id = '"+id+"'");
            rs= pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)jTable2.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
                Vector v= new Vector();
                for(int i=0; i<=c; i++)
                {
                    v.add(rs.getString("id"));
                     v.add(rs.getString("SName"));
                      
                       v.add(rs.getString("phone"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("age"));
                  
                }
                d.addRow(v);   
            }
            
        }catch(SQLException ex)
        {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         JFileChooser fileChooser = new JFileChooser();
          fileChooser.setCurrentDirectory(new File(System.getProperty( "user.home")));
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
          fileChooser.addChoosableFileFilter(filter);
          int result = fileChooser.showSaveDialog(null);
          if(result == JFileChooser.APPROVE_OPTION)
            {
               File selectedFile = fileChooser.getSelectedFile();
               String path = selectedFile.getAbsolutePath();
               lb.setIcon(ResizeImage(path));
               s = path;
            }
          else if(result == JFileChooser.CANCEL_OPTION)
          {
            System.out.println("No Data");
            
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
       Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root","Prbarik528@gmail.com"); 
       PreparedStatement ps = con.prepareStatement("INSERT INTO `online_exam`.`img` (`image`) VALUES (?)");
        if(con!=null){ System.out.println("CONNECTION OK......");}
      else{ System.out.println("TRY AGAIN NO CONNECTION !!!!!!!!");} 
       InputStream is = new FileInputStream(new File(s));
               
       
       ps.setBlob(1,is);
       ps.executeUpdate();
       JOptionPane.showMessageDialog(null,"Data inserted");
       
       
    }catch(Exception ex){ex.printStackTrace();}
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void retriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retriveActionPerformed
        // TODO add your handling code here:
          try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root","Prbarik528@gmail.com");
                if(con!=null){ System.out.println("CONNECTION OK......");}
      else{ System.out.println("TRY AGAIN NO CONNECTION !!!!!!!!");} 
             Statement st = con.createStatement();
                
                ResultSet rs = st.executeQuery("SELECT * FROM online_exam.img");
                
                if(rs.next()){
                          
                    System.out.print("exit");
                    
                    byte[] img = rs.getBytes("image");

                       

                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lb.getWidth(),lb.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lb.setIcon(newImage);
                    
                }
                
                else{
                    System.out.print("not exit");
                    JOptionPane.showMessageDialog(null, "No Data");
                    
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        
    }//GEN-LAST:event_retriveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
             String id= JOptionPane.showInputDialog("enter your id");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root","Prbarik528@gmail.com");
                if(con!=null){ System.out.println("CONNECTION OK......");}
      else{ System.out.println("TRY AGAIN NO CONNECTION !!!!!!!!");} 
             Statement st = con.createStatement();
                
                ResultSet rs = st.executeQuery("SELECT image FROM `online_exam`.`admin` WHERE RegdID = '"+id+"'");
                
                if(rs.next()){
                          
                    System.out.print("exit");
                    
                    byte[] img = rs.getBytes("image");

                       

                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(lb1.getWidth(),lb1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lb1.setIcon(newImage);
                    
                }
                
                else{
                    System.out.print("not exit");
                    JOptionPane.showMessageDialog(null, "No Data");
                    
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
           String sc=jComboBox1.getSelectedItem().toString();
           
            //'"+id+"' sc
            String id1 = id.getText();
              String s= "admin";
            String s1= "student";
            if(s1.equals(sc))
            {
            pst = con.prepareStatement("SELECT * FROM online_exam."+sc+" WHERE SName ='"+id1+"'");
        //    pst = con.prepareStatement("SELECT * FROM online_exam."+sc+" WHERE RegdID ='"+id1+"'");
            rs= pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)jTable2.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
               // jTable2.setVisible(true);
                Vector v= new Vector();
                for(int i=0; i<=c; i++)
                {
                    v.add(rs.getString("id"));
                     v.add(rs.getString("SName"));
                      
                       v.add(rs.getString("phone"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("age"));
                  
                        
                }
                d.addRow(v);   
            }
            }
            else if(s.equals(sc))
            {
              //  pst = con.prepareStatement("SELECT * FROM online_exam."+sc+" WHERE SName ='"+id1+"'");
            pst = con.prepareStatement("SELECT * FROM online_exam."+sc+" WHERE Name ='"+id1+"'");
            rs= pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)jTable2.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
               // jTable2.setVisible(true);
                Vector v= new Vector();
                for(int i=0; i<=c; i++)
                {
                    v.add(rs.getString("RegdID"));
                     v.add(rs.getString("Name"));
                      
                       v.add(rs.getString("Email"));
                        v.add(rs.getString("Phone"));
                        //v.add(rs.getString("age"));
                  
                        
                }
                d.addRow(v);   
            }
            }
            
        }catch(SQLException ex)
        {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentHidden

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //jTable2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
      //  String sc=jComboBox1.getSelectedItem().toString();
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
     public ImageIcon ResizeImage(String imgPath)
            {
                ImageIcon MyImage = new ImageIcon(imgPath);
                Image img = MyImage.getImage();
                Image newImage = img.getScaledInstance(lb.getWidth(),lb.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                return image;
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
               //new LOADING().setVisible(true);
                // loadingg();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtf;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JButton retrive;
    // End of variables declaration//GEN-END:variables
}
