/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pramod
 */
public class Questions extends javax.swing.JFrame {

    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
        connect();
        txtid.setText(String.valueOf(getBill()));
    }
    
    Connection con;
    PreparedStatement pst;
    
    public void connect()
    {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root", "Prbarik528@gmail.com");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public int getBill()
    {
        int billno=1;
       
        try {
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select max(id) from question");
            rs.next();
            billno=rs.getInt(1)+1;
            rs.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        return billno;
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtans = new javax.swing.JTextField();
        txtop4 = new javax.swing.JTextField();
        txtop3 = new javax.swing.JTextField();
        txtop2 = new javax.swing.JTextField();
        txtquestion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtop1 = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        c = new javax.swing.JLabel();
        q = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        o4 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        o3 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        HOME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close2.png"))); // NOI18N
        jLabel10.setText(" ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png"))); // NOI18N
        home.setText(" ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aq+b.png"))); // NOI18N
        add.setText(" ");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Questions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 33, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Question Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Questions");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("option1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("option2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("option3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("option4");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Answer");

        txtid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 0, 0));
        txtid.setText(" ");

        txtans.setBackground(new java.awt.Color(51, 204, 0));
        txtans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtans.setText(" ");

        txtop4.setBackground(new java.awt.Color(255, 102, 0));
        txtop4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtop4.setText(" ");
        txtop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtop4ActionPerformed(evt);
            }
        });

        txtop3.setBackground(new java.awt.Color(255, 102, 0));
        txtop3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtop3.setText(" ");

        txtop2.setBackground(new java.awt.Color(255, 102, 0));
        txtop2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtop2.setText(" ");

        txtquestion.setBackground(new java.awt.Color(0, 0, 204));
        txtquestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtquestion.setForeground(new java.awt.Color(255, 0, 0));
        txtquestion.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Course Code  :");

        txtop1.setBackground(new java.awt.Color(255, 102, 0));
        txtop1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtop1.setText(" ");

        txtcode.setBackground(new java.awt.Color(51, 255, 255));
        txtcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcode.setText(" ");
        txtcode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c.setForeground(new java.awt.Color(255, 0, 0));
        c.setText(" ");

        q.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q.setForeground(new java.awt.Color(255, 0, 0));
        q.setText(" ");

        o1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        o1.setForeground(new java.awt.Color(255, 0, 0));
        o1.setText(" ");

        o4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        o4.setForeground(new java.awt.Color(255, 0, 0));
        o4.setText(" ");

        o2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        o2.setForeground(new java.awt.Color(255, 0, 0));
        o2.setText(" ");

        o3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        o3.setForeground(new java.awt.Color(255, 0, 0));
        o3.setText(" ");

        a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a.setForeground(new java.awt.Color(255, 0, 0));
        a.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtop4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtop3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtop1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtop2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(txtid)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcode, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtquestion))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtid))
                    .addComponent(txtcode)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtop4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        HOME.setBackground(new java.awt.Color(255, 102, 0));
        HOME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HOME.setForeground(new java.awt.Color(255, 0, 0));
        HOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/!yellow.jpg"))); // NOI18N
        HOME.setText(" ");
        HOME.setOpaque(true);
        getContentPane().add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtop4ActionPerformed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aq+b.png")));
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aq+g.png")));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        
        if(txtcode.getText().trim().isEmpty() && txtans.getText().trim().isEmpty() && txtquestion.getText().trim().isEmpty() &&
           txtop1.getText().trim().isEmpty() && txtop2.getText().trim().isEmpty() && txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty() )
        {
            c.setText("* Field requied");
            q.setText("* Field requied");
            o1.setText("* Field requied");
            o2.setText("* Field requied");
            o3.setText("* Field requied");
            o4.setText("* Field requied");
            a.setText("* Field requied");
        }
         
        
        else if(txtcode.getText().trim().isEmpty())
        {
            c.setText("* Field requied");
            q.setText("  ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText(" ");
        }
        else if(txtquestion.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText(" * Field requied ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText(" ");
        }
        else if(txtop1.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText("  ");
            o1.setText("* Field requied ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText(" ");
        }
        else if(txtop2.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText("  ");
            o1.setText(" ");
            o2.setText("* Field requied ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText(" ");
        }
        else if(txtop3.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText("  ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText("* Field requied ");
            o4.setText(" ");
            a.setText(" ");
        }
        else if(txtop4.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText("  ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText("* Field requied ");
            a.setText(" ");
        }
        else if(txtans.getText().trim().isEmpty())
        {
            c.setText(" ");
            q.setText("  ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText("* Field requied ");
        }
        else if(   txtop4.getText().trim().isEmpty())
        {
           // c.setText("* Field requied");
           // q.setText("* Field requied");
           // o1.setText("* Field requied");
           // o2.setText("* Field requied");
           // o3.setText("* Field requied");
            o4.setText("* Field requied");
           // a.setText("* Field requied");
        }
        else if(  txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty())
        {
            //c.setText("* Field requied");
            //q.setText("* Field requied");
            //o1.setText("* Field requied");
            //o2.setText("* Field requied");
             o3.setText("* Field requied");
             o4.setText("* Field requied");
            //a.setText("* Field requied");
        }
        else if(txtop2.getText().trim().isEmpty() && txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty())
        {
            //c.setText("* Field requied");
           // q.setText("* Field requied");
            //o1.setText("* Field requied");
            o2.setText("* Field requied");
            o3.setText("* Field requied");
            o4.setText("* Field requied");
           // a.setText("* Field requied");
        }
        else if(txtop1.getText().trim().isEmpty() && txtop2.getText().trim().isEmpty() && txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty())
        {
           // c.setText("* Field requied");
           // q.setText("* Field requied");
            o1.setText("* Field requied");
            o2.setText("* Field requied");
            o3.setText("* Field requied");
            o4.setText("* Field requied");
            //a.setText("* Field requied");
        }
        else if(txtquestion.getText().trim().isEmpty() &&
           txtop1.getText().trim().isEmpty() && txtop2.getText().trim().isEmpty() && txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty())
        {
            //c.setText("* Field requied");
            q.setText("* Field requied");
            o1.setText("* Field requied");
            o2.setText("* Field requied");
            o3.setText("* Field requied");
            o4.setText("* Field requied");
        }
        else if( txtans.getText().trim().isEmpty() && txtquestion.getText().trim().isEmpty() &&
           txtop1.getText().trim().isEmpty() && txtop2.getText().trim().isEmpty() && txtop3.getText().trim().isEmpty() && txtop4.getText().trim().isEmpty())
        {
             q.setText("* Field requied");
            o1.setText("* Field requied");
            o2.setText("* Field requied");
            o3.setText("* Field requied");
            o4.setText("* Field requied");
            a.setText("* Field requied");
        }
        else
        {
             c.setText(" ");
            q.setText("  ");
            o1.setText(" ");
            o2.setText(" ");
            o3.setText(" ");
            o4.setText(" ");
            a.setText(" ");
        }
        
         try {
            // TODO add your handling code here:
            String id = txtid.getText();
        String question=txtquestion.getText();
        String op1=txtop1.getText();
        String op2=txtop2.getText();
        String op3=txtop3.getText();
        String op4=txtop4.getText();
        String answer=txtans.getText();
          String code=txtcode.getText();
          
            pst= con.prepareStatement("INSERT INTO `online_exam`.`question`(`id`,`Question`,`option1`,`option2`,`option3`,`option4`,`answer`,`code`)values(?,?,?,?,?,?,?,?)");
            pst.setString(1,id);
            pst.setString(2,question);
            pst.setString(3,op1);
            pst.setString(4,op2);
            pst.setString(5,op3);
            pst.setString(6,op4);
            pst.setString(7,answer);
             pst.setString(8,code);
            
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"QUESTION added");
                
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addMouseClicked

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
         home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png")));
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
         home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+g.png")));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
          new welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( HOME,"confirm if you Want to Exit","ONLINE EXAMINATION APPLICATION",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME;
    private javax.swing.JLabel a;
    private javax.swing.JLabel add;
    private javax.swing.JLabel c;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JLabel o3;
    private javax.swing.JLabel o4;
    private javax.swing.JLabel q;
    private javax.swing.JTextField txtans;
    private javax.swing.JTextField txtcode;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtop1;
    private javax.swing.JTextField txtop2;
    private javax.swing.JTextField txtop3;
    private javax.swing.JTextField txtop4;
    private javax.swing.JTextField txtquestion;
    // End of variables declaration//GEN-END:variables
}
