/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pramod
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
        connect();
        load();
    }
    String s;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void connect()
    {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online_exam","root", "Prbarik528@gmail.com");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void load()
    {
        try{
            pst = con.prepareStatement("SELECT * FROM online_exam.student");
            rs= pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
                Vector v= new Vector();
                for(int i=0; i<=c; i++)
                {
                    v.add(rs.getString("id"));
                     v.add(rs.getString("SName"));
                      
                       v.add(rs.getString("phone"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("age"));
                  
                }
                d.addRow(v);   
            }
            
        }catch(SQLException ex)
        {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        clr = new javax.swing.JLabel();
        deletee = new javax.swing.JLabel();
        editt = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        HOME = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 255, 255));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Phone", "Address", "AGE"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 450, 210));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Student Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("phone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age");

        txtphone.setBackground(new java.awt.Color(0, 204, 255));
        txtphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtphone.setText(" ");
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });

        txtname.setBackground(new java.awt.Color(0, 204, 255));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtname.setText(" ");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        txtage.setBackground(new java.awt.Color(0, 204, 255));
        txtage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtage.setText(" ");
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        txtaddress.setBackground(new java.awt.Color(0, 204, 255));
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtaddress.setText(" ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/name (2).png"))); // NOI18N
        jLabel7.setText(" ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/phone (2).png"))); // NOI18N
        jLabel9.setText(" ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/address.png"))); // NOI18N
        jLabel10.setText(" ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/age.png"))); // NOI18N
        jLabel11.setText(" ");

        ph.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ph.setForeground(new java.awt.Color(255, 0, 0));
        ph.setText(" ");

        nm.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 0, 0));
        nm.setText(" ");

        age.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        age.setForeground(new java.awt.Color(255, 0, 0));
        age.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(txtage, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(txtname)
                        .addComponent(ph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1)
                        .addComponent(nm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9)))
                .addGap(3, 3, 3)
                .addComponent(ph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel10)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close2.png"))); // NOI18N
        jLabel12.setText(" ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jButton1.setText("Upload Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        lb1.setText(" ");
        lb1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 140, 130));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png"))); // NOI18N
        home.setText(" ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/c+b.png"))); // NOI18N
        clr.setText(" ");
        clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clrMouseExited(evt);
            }
        });
        getContentPane().add(clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        deletee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/d+b.png"))); // NOI18N
        deletee.setText(" ");
        deletee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteeMouseExited(evt);
            }
        });
        getContentPane().add(deletee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        editt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/e+b.png"))); // NOI18N
        editt.setText(" ");
        editt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edittMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edittMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edittMouseExited(evt);
            }
        });
        getContentPane().add(editt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/a+b.png"))); // NOI18N
        add.setText(" ");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        HOME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/!yellow.jpg"))); // NOI18N
        HOME.setText(" ");
        getContentPane().add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
         int selectindex = jTable1.getSelectedRow();
         String id = d.getValueAt(selectindex,0).toString();
         txtname.setText(d.getValueAt(selectindex,1).toString());
         txtphone.setText(d.getValueAt(selectindex,2).toString());
         txtaddress.setText(d.getValueAt(selectindex,3).toString());
         txtage.setText(d.getValueAt(selectindex,4).toString());
         
         add.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/a+b.png")));
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/a+g.png")));
    }//GEN-LAST:event_addMouseEntered

    private void edittMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittMouseExited
        // TODO add your handling code here:
        editt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/e+b.png")));
    }//GEN-LAST:event_edittMouseExited

    private void edittMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittMouseEntered
        // TODO add your handling code here:
        editt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/e+g.png")));
    }//GEN-LAST:event_edittMouseEntered

    private void deleteeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteeMouseExited
        // TODO add your handling code here:
        deletee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/d+b.png"))); 
    }//GEN-LAST:event_deleteeMouseExited

    private void deleteeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteeMouseEntered
        // TODO add your handling code here:
        deletee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/d+g.png"))); 
    }//GEN-LAST:event_deleteeMouseEntered

    private void clrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMouseExited
        // TODO add your handling code here:
        clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/c+b.png")));
    }//GEN-LAST:event_clrMouseExited

    private void clrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMouseEntered
        // TODO add your handling code here:
        clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/exam/image/c+g.png")));
    }//GEN-LAST:event_clrMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        
        
        try {
           
            String stname = txtname.getText();
            String phone = txtphone.getText();
            String address = txtaddress.getText();
            String age = txtage.getText();
            InputStream is = null;
             try {
                 is = new FileInputStream(new File(s));
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            pst= con.prepareStatement("INSERT INTO `online_exam`.`student`(`SName`,`phone`,`address`,`age`,`image`)values(?,?,?,?,?)");
            pst.setString(1,stname);
            pst.setString(2,phone);
            pst.setString(3,address);
            pst.setString(4,age);
             pst.setBlob(5,is);
            
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record added");
                txtname.setText("");
                txtphone.setText("");
                txtaddress.setText("");
                txtage.setText("");
                txtname.requestFocus();
                load();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

                                    

    private void editActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
      
           try {
            // TODO add your handling code here:
            
             DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
             int selectindex = jTable1.getSelectedRow();
         
            String stname = txtname.getText();
            String phone = txtphone.getText();
            String address = txtaddress.getText();
            String age = txtage.getText();
            String id = d.getValueAt(selectindex,0).toString();
            
            pst= con.prepareStatement("UPDATE `online_exam`.`student` SET  `SName` =  ?,`phone` = ?,`address` = ?,`age` = ? WHERE `id` = ?");
            pst.setString(1,stname);
            pst.setString(2,phone);
            pst.setString(3,address);
            pst.setString(4,age);
             pst.setString(5,id);
            
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record Edited");
                txtname.setText("");
                txtphone.setText("");
                txtaddress.setText("");
                txtage.setText("");
                txtname.requestFocus();
                add.setEnabled(true);
                load();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
        
    }//GEN-LAST:event_addMouseClicked

    private void edittMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittMouseClicked
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            
             DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
             int selectindex = jTable1.getSelectedRow();
         
            String stname = txtname.getText();
            String phone = txtphone.getText();
            String address = txtaddress.getText();
            String age = txtage.getText();
            String id = d.getValueAt(selectindex,0).toString();
            
            pst= con.prepareStatement("UPDATE `online_exam`.`student` SET  `SName` =  ?,`phone` = ?,`address` = ?,`age` = ? WHERE `id` = ?");
            pst.setString(1,stname);
            pst.setString(2,phone);
            pst.setString(3,address);
            pst.setString(4,age);
             pst.setString(5,id);
            
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record Edited");
                txtname.setText("");
                txtphone.setText("");
                txtaddress.setText("");
                txtage.setText("");
                txtname.requestFocus();
                add.setEnabled(true);
                load();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    
        
    }//GEN-LAST:event_edittMouseClicked

    private void deleteeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteeMouseClicked
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            
             DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
             int selectindex = jTable1.getSelectedRow();
         
           
             
            String id = d.getValueAt(selectindex,0).toString();
            
            pst= con.prepareStatement("DELETE FROM `online_exam`.`student` WHERE `id` = ?");
            
            
             pst.setString(1,id);
            
            int k=pst.executeUpdate();
            if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record Deleted");
                txtname.setText("");
                txtphone.setText("");
                txtaddress.setText("");
                txtage.setText("");
                txtname.requestFocus();
                 add.setEnabled(true);
                load();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Record added fail");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_deleteeMouseClicked

    private void clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMouseClicked
        // TODO add your handling code here:
         txtname.setText("");
                txtphone.setText("");
                txtaddress.setText("");
                txtage.setText("");
                txtname.requestFocus();
                 add.setEnabled(true);
                load();
    }//GEN-LAST:event_clrMouseClicked

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
         home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+b.png")));
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
         home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hm+g.png")));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
         new welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
          fileChooser.setCurrentDirectory(new File(System.getProperty( "user.home")));
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
          fileChooser.addChoosableFileFilter(filter);
          int result = fileChooser.showSaveDialog(null);
          if(result == JFileChooser.APPROVE_OPTION)
            {
               File selectedFile = fileChooser.getSelectedFile();
               String path = selectedFile.getAbsolutePath();
               lb1.setIcon(ResizeImage(path));
               s = path;
            }
          else if(result == JFileChooser.CANCEL_OPTION)
          {
            System.out.println("No Data");
            
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( HOME,"confirm if you Want to Exit","ONLINE EXAMINATION APPLICATION",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
         {
             txtname.setEditable(true);
         }
         else
         {
             txtname.setEditable(false);
             nm.setText("Character's only allowed");
             JOptionPane.showMessageDialog(this, "Plaese Enter only Character ");
             
            
         }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        
        String ph1=txtphone.getText();
        int length=ph1.length();
        
        char c=evt.getKeyChar();
         if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
         {
             if(length<10){
             txtphone.setEditable(true);
            // ph.setText("  Number's only allowed");
             //JOptionPane.showMessageDialog(this, "Plaese Enetr only number's");
             }
             else
             {
                 txtphone.setEditable(false);
                   //ph.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, " Can't exceed more than 10 digit");
             }
         }
         else
         {
           //  txtphone.setEditable(true);
            // ph.setText("Number's only allowed");
            // JOptionPane.showMessageDialog(this, "Plaese Enetr only Character ");
             
             if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                txtphone.setEditable(true); 
             }
             else
             {
                 txtphone.setEditable(false);
                   ph.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, "Plaese Enter only number's");
             }
             
            
         }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
        String ph1=txtage.getText();
        int length=ph1.length();
        
        char c=evt.getKeyChar();
         if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
         {
             if(length<2){
             txtage.setEditable(true);
            // ph.setText("  Number's only allowed");
             //JOptionPane.showMessageDialog(this, "Plaese Enetr only number's");
             }
             else
             {
                 txtage.setEditable(false);
                   //ph.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, " Can't exceed more than 10 digit");
             }
         }
         else
         {
           //  txtphone.setEditable(true);
            // ph.setText("Number's only allowed");
            // JOptionPane.showMessageDialog(this, "Plaese Enetr only Character ");
             
             if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                txtage.setEditable(true); 
             }
             else
             {
                 txtage.setEditable(false);
                   age.setText("  Number's only allowed");
             JOptionPane.showMessageDialog(this, "Plaese Enter only number's");
             }
             
            
         }
    }//GEN-LAST:event_txtageKeyPressed

     public ImageIcon ResizeImage(String imgPath)
            {
                ImageIcon MyImage = new ImageIcon(imgPath);
                Image img = MyImage.getImage();
                Image newImage = img.getScaledInstance(lb1.getWidth(),lb1.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                return image;
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mental".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME;
    private javax.swing.JLabel add;
    private javax.swing.JLabel age;
    private javax.swing.JLabel clr;
    private javax.swing.JLabel deletee;
    private javax.swing.JLabel editt;
    private javax.swing.JLabel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel nm;
    private javax.swing.JLabel ph;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
