/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.exam;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pramod
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        gif.setIcon(new ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\online exam\\src\\online\\exam\\gif.gif"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        copy = new javax.swing.JLabel();
        Sregd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regdA = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        gif = new javax.swing.JLabel();
        SRCH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HOME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close2.png"))); // NOI18N
        jLabel3.setText(" ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        copy.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        copy.setForeground(new java.awt.Color(255, 255, 0));
        copy.setText(" Copyright © Online Examination System ® Pramod kumar barik Development ™");
        copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copyMouseExited(evt);
            }
        });
        getContentPane().add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 700, 40));

        Sregd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Sregd.setForeground(new java.awt.Color(255, 255, 0));
        Sregd.setText("Student Registration");
        Sregd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SregdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SregdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SregdMouseExited(evt);
            }
        });
        getContentPane().add(Sregd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("||");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        regdA.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        regdA.setForeground(new java.awt.Color(255, 255, 0));
        regdA.setText("Admin Registration");
        regdA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regdAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regdAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regdAMouseExited(evt);
            }
        });
        getContentPane().add(regdA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sl+yy.png"))); // NOI18N
        b5.setText(" ");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, 40));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a+y.png"))); // NOI18N
        b2.setText(" ");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 40));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/i+y.png"))); // NOI18N
        b3.setText(" ");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 40));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/al+yy.png"))); // NOI18N
        b4.setText(" ");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b4MouseReleased(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 40));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/h+y.png"))); // NOI18N
        b1.setText(" ");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 50));

        gif.setText(" ");
        getContentPane().add(gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 720, 340));

        SRCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s+y.png"))); // NOI18N
        SRCH.setText(" ");
        SRCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SRCHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SRCHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SRCHMouseExited(evt);
            }
        });
        getContentPane().add(SRCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("ONLINE EXAMINATION APPLICATION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText(" Computer Base Exams");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setText(" ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 630));

        jLabel4.setBackground(new java.awt.Color(204, 0, 51));
        jLabel4.setText(" ");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 770, 630));

        HOME.setText(" ");
        getContentPane().add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/h+r.png")));
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/h+y.png")));

    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        // TODO add your handling code here:
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aa+r.png")));
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        // TODO add your handling code here:
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a+y.png")));
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        // TODO add your handling code here:
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/i+r.png")));
    }//GEN-LAST:event_b3MouseEntered

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        // TODO add your handling code here:
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/i+y.png")));
    }//GEN-LAST:event_b3MouseExited

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        // TODO add your handling code here:
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/al+rr.png")));
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        // TODO add your handling code here:
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/al+yy.png")));
    }//GEN-LAST:event_b4MouseExited

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        // TODO add your handling code here:
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sl+rr.png")));
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        // TODO add your handling code here:
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sl+yy.png")));
    }//GEN-LAST:event_b5MouseExited

    private void regdAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdAMouseEntered
        // TODO add your handling code here:
        regdA.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        regdA.setForeground(new java.awt.Color(255, 51, 51));
        regdA.setText("Admin Registration");
    }//GEN-LAST:event_regdAMouseEntered

    private void regdAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdAMouseExited
        // TODO add your handling code here:
        regdA.setForeground(new java.awt.Color(255, 255, 0));

    }//GEN-LAST:event_regdAMouseExited

    private void SregdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SregdMouseExited
        // TODO add your handling code here:
        Sregd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Sregd.setForeground(new java.awt.Color(255, 255, 0));
        Sregd.setText("Student Registration");
    }//GEN-LAST:event_SregdMouseExited

    private void SregdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SregdMouseEntered
        // TODO add your handling code here:
        Sregd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Sregd.setForeground(new java.awt.Color(255, 0, 0));

        Sregd.setText("Student Registration");
    }//GEN-LAST:event_SregdMouseEntered

    private void copyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyMouseExited
        // TODO add your handling code here:
        copy.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
         copy.setForeground(new java.awt.Color(255, 255, 0));
        copy.setText(" Copyright © Online Examination System ® Pramod kumar barik Development ™");
    }//GEN-LAST:event_copyMouseExited

    private void copyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyMouseEntered
        // TODO add your handling code here:
        copy.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        copy.setForeground(new java.awt.Color(51, 51, 255));
        copy.setText(" Copyright © Online Examination System ® Pramod kumar barik Development ™");
    }//GEN-LAST:event_copyMouseEntered

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // TODO add your handling code here:
        new admin_login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b4MouseClicked

    private void b4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_b4MousePressed

    private void b4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_b4MouseReleased

    private void regdAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regdAMouseClicked
        // TODO add your handling code here:
        new admin_Regd().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regdAMouseClicked

    private void SregdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SregdMouseClicked
        // TODO add your handling code here:
        new student().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SregdMouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        // TODO add your handling code here:
        new Student_login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b5MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
        new Instraction_Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b3MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
        new About().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( HOME,"confirm if you Want to Exit","ONLINE EXAMINATION APPLICATIOM",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void SRCHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SRCHMouseExited
        // TODO add your handling code here:
        SRCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s+y.png")));
    }//GEN-LAST:event_SRCHMouseExited

    private void SRCHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SRCHMouseEntered
        // TODO add your handling code here:
        SRCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ss+r.png")));
    }//GEN-LAST:event_SRCHMouseEntered

    private void SRCHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SRCHMouseClicked
        // TODO add your handling code here:
        new search().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SRCHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME;
    private javax.swing.JLabel SRCH;
    private javax.swing.JLabel Sregd;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel copy;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel regdA;
    // End of variables declaration//GEN-END:variables
}
